name: Next release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release branch code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org

      - name: NPM Install
        run: npm i

      - name: NPM Build
        run: npm run build

      - name: Dir ls
        run: dir

      - name: Publish to NPM
        run: npm run update:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
